### ISSUE TITLE
Open Sourced Alternative to Boxcryptor?

### ISSUE THREAD

**Issue by wangkesen** [mgoellnitz/JFileSync3#2]
Just wondering if it's possible to use with an _open-sourced_ alternative in place Boxcryptor?
[Cryptomator](https://cryptomator.org ) perhaps?

Been looking for a sync alternative like this for a while but encryption is important to many and a lot of critique will result from Boxcryptor I feel since they aren't open-sourced. If there is already a way to incorporate this with Cryptomator or another open-sourced encryption method please let me know! Thanks!

**Comment by mgoellnitz** [comment]
When I mention Boxcryptor here, it always relates to the old EncFS-based "classic" version (1.x). So, that being said, there are open-sourced alternatives which are interoperable with the EncFS part of JFileSync3 like encfs4win or cryptkeeper.

I didn't come accross Cryptomator up to now and didn't take a deeper look into it. It seems to share certain concepts with JFileSync3 like filename encryption, name-shortening, generic storage locations.

The main difference is, that Cryptomator works online but is limited to WebDAV as its frontend, while JFileSync3 works offline with references to local files - so you can directly operate on the later synced files, which is not fully possible with WebDAV even on Linux.

So, if you are asking for open-sourced encryption and syncing: This is already accomplished. On the other hand I right now don't see a point for interoperation with Cryptomator which seems to be an alternative to JFileSync3 with different focus.

**Comment by mgoellnitz** [comment]
Closing this, this JFilesSync3 and Cryptomator both are open source alternatives to the proprietary Boxcryptor.
